name: OWASP Dependency Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run OWASP Dependency-Check
        uses: dependency-check/dependency-check-action@v2
        with:
          project: AppReceitas
          scan: .
          format: "HTML"
